Release v1.2.0

diff --git a/tools/cfn-templates/fwdemo.yml b/tools/cfn-templates/fwdemo.yml
--- a/tools/cfn-templates/fwdemo.yml
+++ b/tools/cfn-templates/fwdemo.yml
@@ -142,9 +142,28 @@ Resources:
             systemctl stop unattended-upgrades
             systemctl disable unattended-upgrades
 
+            # Wait for any existing package install to finish
+            i=0
+            while true; do
+              if sudo fuser /var/{lib/{dpkg,apt/lists},cache/apt/archives}/lock >/dev/null 2>&1; then
+                i=0
+              else
+                i=`expr $i + 1`
+                if expr $i \>= 10 > /dev/null; then
+                  break
+                fi
+              fi
+              sleep 1
+            done
+
+            print_process_list() {
+              ps aux # Print processes on error in case apt lock was still taken
+            }
+            trap print_process_list ERR
+
             # Upgrade system and reboot if required
-            apt update -o DPkg::Lock::Timeout=120
-            apt upgrade -y -o DPkg::Lock::Timeout=120
+            apt update
+            apt upgrade -y
             if [ -f /var/run/reboot-required ]; then
               # Delete the UserData info file so that we run again after reboot
               rm -f /var/lib/cloud/instances/*/sem/config_scripts_user
@@ -153,8 +172,8 @@ Resources:
             fi
 
             # Install helper scripts:
-            apt update -o DPkg::Lock::Timeout=120
-            apt install -y -o DPkg::Lock::Timeout=120 python3-setuptools
+            apt update
+            apt install -y python3-setuptools
             mkdir -p /opt/aws/bin
             wget https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-py3-latest.tar.gz
             python3 -m easy_install --script-dir /opt/aws/bin aws-cfn-bootstrap-py3-latest.tar.gz
@@ -162,6 +181,7 @@ Resources:
 
             # On error, signal back to cfn:
             error_handler() {
+              print_process_list
               /opt/aws/bin/cfn-signal --success false --stack ${AWS::StackName} --resource Ec2Instance --region ${AWS::Region}
             }
             trap error_handler ERR
@@ -174,8 +194,8 @@ Resources:
             printf "RateLimitBurst=0\nSystemMaxUse=1G\n" >> /etc/systemd/journald.conf
 
             # Install packages
-            apt update -o DPkg::Lock::Timeout=120
-            apt install -y -o DPkg::Lock::Timeout=120 wget ec2-instance-connect htop jq unzip
+            apt update
+            apt install -y wget ec2-instance-connect htop jq unzip
 
             # Install AWS CLI:
             curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip"
@@ -230,7 +250,7 @@ Resources:
                 --log-level ${FweLogLevel} \
                 --vehicle-name "${AWS::StackName}" \
                 --endpoint-url "${IoTThing.iotEndpoint}" \
-                --topic-prefix '${IoTMqttTopicPrefix}' \
+                --iotfleetwise-topic-prefix '${IoTMqttTopicPrefix}' \
                 --can-bus0 "vcan0" \
                 ${!VISION_SYSTEM_DATA_OPTIONS}
             else
@@ -247,7 +267,7 @@ Resources:
                       --output-config-file "/etc/aws-iot-fleetwise/config-$((i+j)).json" \
                       --vehicle-name "${AWS::StackName}-$((i+j))" \
                       --endpoint-url "${IoTThing.iotEndpoint}" \
-                      --topic-prefix '${IoTMqttTopicPrefix}' \
+                      --iotfleetwise-topic-prefix '${IoTMqttTopicPrefix}' \
                       --can-bus0 "vcan$((i+j))" \
                       --persistency-path "/var/aws-iot-fleetwise/fwe$((i+j))" \
                       ${!VISION_SYSTEM_DATA_OPTIONS}; \
@@ -263,10 +283,6 @@ Resources:
 
             # Signal init complete:
             /opt/aws/bin/cfn-signal --stack ${AWS::StackName} --resource Ec2Instance --region ${AWS::Region}
-
-            # Re-enable unattended upgrades
-            systemctl enable unattended-upgrades
-            systemctl start unattended-upgrades
   Ec2Instance:
     Type: AWS::EC2::Instance
     CreationPolicy:
